model_2D:
  - ResUNet_LSTM

WHS_datasets:
  ct:
    train_paths:
      - "/content/drive/MyDrive/cardiac-project//data/converted/ct/train"
    val_path: "/content/drive/MyDrive/cardiac-project/data/converted/ct/val"
    test_path: "/content/drive/MyDrive/cardiac-project/data/converted/ct/test"
    results_output:
      statistics: "/content/drive/MyDrive/cardiac-project/ct_reslstmunet_run/statistics"
      model_state_dict: "/content/drive/MyDrive/cardiac-project/ct_reslstmunet_run/checkpoints"

  mr:
    train_paths:
      - "/content/drive/MyDrive/cardiac-project/data/converted/mr/train"
    val_path: "/content/drive/MyDrive/cardiac-project/data/converted/mr/val"
    test_path: "/content/drive/MyDrive/cardiac-project/data/converted/mr/test"
    results_output:
      statistics: "/content/drive/MyDrive/cardiac-project/mr_reslstmunet_run/statistics"
      model_state_dict: "/content/drive/MyDrive/cardiac-project/mr_reslstmunet_run/checkpoints"
