model_2D:
  - ResUNet_LSTM

WHS_datasets:
  # # List of directories used for training (one entry per source)
  # train_paths:
  #   - "/Users/erinsarlak/Desktop/MedicalImagingProject/data/converted/ct/train"

  # # Directory used for validation during training
  # test_path: "/Users/erinsarlak/Desktop/MedicalImagingProject/data/converted/ct/test"

  # results_output:
  #   statistics: "/Users/erinsarlak/Desktop/MedicalImagingProject/cardiac-image-segmentation-project/output/statistics"
  #   model_state_dict: "/Users/erinsarlak/Desktop/MedicalImagingProject/cardiac-image-segmentation-project/output/checkpoints"

  train_paths:
    - "/content/drive/MyDrive/cardiac-project/data/converted/ct/train"
  test_path: "/content/drive/MyDrive/cardiac-project/data/converted/ct/test"
  results_output:
    statistics: "/content/drive/MyDrive/cardiac-project/output_aug/statistics"
    model_state_dict: "/content/drive/MyDrive/cardiac-project/output_aug/checkpoints"